### PR TITLE
Fix for Anki version 24.04+; Fix second refresh after loading note; Fix memory leakage

### LINKED ISSUE #22: Bug: After displaying the preview, it will refresh again
When JavaScript is used for rendering operations in the card, such as rendering Markdown, it can be seen that there is a second refresh process after the note is loaded.

GIF 2024-2-2 7-38-50

### PR DESCRIPTION
**Pull request by gugutu**
Fix #22 
Fix memory leakage caused by hook not releasing 
Improve compatibility with other plugins
Fix for Anki version 24.04+

### CODE REVIEW

**Comment by rad4day** [comment]
Just a heads-up: I am pretty busy right now and haven't gotten around to taking a look at this yet. I hope I'll get around to it before end of the week.

On a first glance it looks good though.

**Comment by I-Al-Istannen** [comment]
What exactly does this fix @gugutu? My Anki still looks like this:
image

I am using
```
Version ⁨23.12.1 (1a1d4d54)⁩
Python 3.11.7 Qt 6.6.2 PyQt 6.6.1
```

I assume you are using the 24 betas?

**Comment by gugutu** [comment]
@I-Al-Istannen 

I tested add-on on the Windows platform and found that it works properly on Anki's 23.12.1 and 24.04beta1 versions. Are you using [Editor Live Preview (forked for temporary use)](https://ankiweb.net/shared/info/1685760768) or [Editor Live Preview](https://ankiweb.net/shared/info/1960039667)?

image
image

**Comment by I-Al-Istannen** [comment]
Both, but I am on Linux (Arch Linux, building Anki from source). Maybe it something on my end then. It's a bit weird, it used to work :P

But then it probably does not have anything to do with this PR (though rad4day has the same problem, but also uses the same OS as I do…).

**Comment by gugutu** [comment]
May caused by ankitects/anki#2836

**Comment by gugutu** [comment]
@I-Al-Istannen 

I have updated the [Editor Live Preview (forked for temporary use)](https://ankiweb.net/shared/info/1685760768)，please update the add-on and see if the issue still exists.

**Comment by I-Al-Istannen** [comment]
@gugutu I built the master branch of your fork and it works now :) Thanks!

**Comment by rad4day** [comment]
Can confirm that this works.

I'll get to publishing a new release right now.

Thank you soooo much for those fixes and for looking into that weird anki bug.

**Pull request merged**
