### PR TITLE
Toolbar icon + many new features

### PR DESCRIPTION
**Pull request by kvn1351**
Hi, I've added some features to this addon:

- config file with readme
- default open/close state
- default split ratio
- a pretty nice toolbar icon in vector format (so with dark/light support)

Hope you like it

### CODE REVIEW

**Comment by kvn1351** [comment]
CleanShot 2022-10-09 at 17 28 23

CleanShot 2022-10-09 at 17 28 53

**Comment by rad4day** [comment]
That is indeed very useful!

The only thing I am not so sure about is the origin and the license of the toolbar icon. Google Reverse Image search links me back to [https://www.onlinewebfonts.com/icon/190207](https://www.onlinewebfonts.com/icon/190207) which neither has any information on the license of that icon nor has working privacy/contact us links.

I am inclined to merge this, as it seems to be working and a great improvement to the add-on. But, I can't until the origin and license of that icon is clear OR it is replaced with one with an open license. A bit of [CYA](https://www.urbandictionary.com/define.php?term=cover%20your%20ass) is, sadly, necessary.

**Comment by kvn1351** [comment]
That's indeed the place I've taken it from. Usually, I design them from scratch. But in this case, I didn't want to invest more time than necessary.

That being said, if you download the SVG and compare the code you'll find it's heavily altered.

The positioning of all elements is different. The magnifying glass is also not in the same spot. The lines are also much thicker.

So I really don't see the issue. Especially not for something as simple and mundane as this design. Were we talking about the Nike logo, then I'd fully agree.

**Comment by rad4day** [comment]
> But in this case, I didn't want to invest more time than necessary.

That's obviously fine :D 

> That being said, if you download the SVG and compare the code you'll find it's heavily altered.
The positioning of all elements is different. The magnifying glass is also not in the same spot. The lines are also much thicker.

Oh, I didn't notice that. Indeed, they are quite a bit different.

> So I really don't see the issue. Especially not for something as simple and mundane as this design. Were we talking about the Nike logo, then I'd fully agree.

The site stating it as “FREE” without any license text and no working privacy/contact us links put me a bit on guard.

But it's probably fine. I'll merge this later today as it needs me to make some changes to the .gitignore and the build script.

**Comment by kvn1351** [comment]
Nice 😄

**Comment by rad4day** [comment]
And the changes are live on AnkiWeb now. <3

**Pull request merged**
